name: update-readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: larryh12/github-readme-qotd@main
        with:
          TOKEN: ${{ secrets.REPO_TOKEN }}
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
          COMMIT_MESSAGE: 'Update Wakatime Stats'
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          LANG_COUNT: 5
          BLOCKS: '░▓'
