name: update-readme

on:
  workflow_dispatch:
  
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: larryh12/github-readme-qotd@main
        with:
          TOKEN: ${{ secrets.REPO_TOKEN }}
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.REPO_TOKEN }}
          COMMIT_MESSAGE: 'Update Wakatime Stats'
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          CODE_LANG: py
          LANG_COUNT: 5
          BLOCKS: '░▓'
